### ISSUE TITLE
Allow settings_files to be a list of pathlib.Paths

### ISSUE THREAD

**Issue by dev-zero** [daviskirk/climatecontrol#29]
I just came across this little project, looks really nice!
What I don't get yet is the need for the `settings_files` to be strings, rather than `pathlib.Path`:

https://github.com/daviskirk/climatecontrol/blob/fc84af82205ac7eb728406f542efcb8237293ea1/climatecontrol/core.py#L193

For example I would like to use it like this:

```python
from pathlib import Path
from climatecontrol import Climate

climate = Climate(settings_files=[Path.home() / ".config" / "myapp" / "myapp.json"])
```

but what I get from `mypy` is:

```
$ poetry run mypy --namespace-packages -p myapp
myapp/cli.py:9: error: List item 0 has incompatible type "Path"; expected "str"
Found 1 error in 1 file (checked 3 source files)
```

**Comment by daviskirk** [comment]
I'll look at it.  I don't think there's a reason to restrict it to strings.

I think you can probably do this in the mean time:
```
climate = Climate(settings_files=[str(Path.home() / ".config" / "myapp" / "myapp.json")])
```

**Comment by daviskirk** [comment]
Fee free to check out version 0.10.0 (`pip install climatecontrol==0.10.0`), mypy shouldn't complain about your example any more
